# Generated by Django 4.1.4 on 2022-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yash_emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('base_location', models.CharField(max_length=250)),
                ('current_location', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=100)),
                ('experience_range', models.CharField(max_length=100)),
                ('skill_cluster', models.CharField(max_length=100)),
                ('general_communication', models.CharField(max_length=100)),
                ('attitude', models.CharField(max_length=100)),
                ('core_java', models.CharField(max_length=100)),
                ('advance_java', models.CharField(max_length=100)),
                ('servlet_and_jsp', models.CharField(max_length=100)),
                ('spring_framework', models.CharField(max_length=100)),
                ('spring_mvc', models.CharField(max_length=100)),
                ('spring_security', models.CharField(max_length=100)),
                ('spring_boot', models.CharField(max_length=100)),
                ('struts', models.CharField(max_length=100)),
                ('web_services_rest_api', models.CharField(max_length=100)),
                ('web_services_soap', models.CharField(max_length=100)),
                ('frontend_html_css_javascript', models.CharField(max_length=100)),
                ('frontend_angular', models.CharField(max_length=100)),
                ('frontend_react', models.CharField(max_length=100)),
                ('relational_database', models.CharField(max_length=100)),
                ('non_relational_database', models.CharField(max_length=100)),
                ('orm_jpa_hibernate', models.CharField(max_length=100)),
                ('cloud_tech', models.CharField(max_length=100)),
                ('devops', models.CharField(max_length=100)),
                ('agile', models.CharField(max_length=100)),
                ('location_constraint', models.CharField(max_length=100)),
                ('overall_feedback', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
