# Generated by Django 4.1.4 on 2022-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_associate_advance_java_alter_associate_agile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='yash_emp_id',
            field=models.CharField(max_length=250),
        ),
    ]
