# Generated by Django 4.1.4 on 2022-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_associate_yash_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='date_of_joining',
            field=models.CharField(max_length=250),
        ),
    ]
